### ISSUE TITLE
Change Name of 'Slow 02'

### ISSUE THREAD

**Issue by enter-username-here** [BEEmod/BEE2-music#1]
The song Slow 02 from Aperture Tag isn't actually called that. I presume it's been called that because that's the AT file name (tag_slow_02) and it isn't included in the soundtrack. Well, I found out that the track was originally from a cancelled mod called Tier 3 that Harry101UK composed the soundtrack for, and Slow 02 was called 'Dereliction'. You can find it [here](https://harrycallaghan.bandcamp.com/track/dereliction).

**Comment by electrovoyage** [comment]
Yes, officially the track _is_ called Dereliction however, if you open Aperture Tag's files and dig around for a bit, you will find `slow_02.wav`. That song is Dereliction.
