### ISSUE TITLE
Thinking with Time Machine music

### ISSUE THREAD

**Issue by slambo312** [BEEmod/BEE2-music#10]
Alright I'll be honest. I have no clue whether or not TWTM has it's own soundtrack, but if it does, yeah.

**Comment by FrozenDragon0** [comment]
TWTM Doesn't have it's own Soundtrack, never heard any music in it's campaign.

**Comment by KaziPlays** [comment]
It does, but it has only one song, and it's the main menu music.

**Comment by FrozenDragon0** [comment]
@KaziPlays That's only one track though, not much point in adding it when it just has one track.
