### ISSUE TITLE
Portal Stories: Mel musics does not show up.

### ISSUE THREAD

**Issue by Wilk1910** [BEEmod/BEE2-music#12]
So honestly, i installed the bee2 mod with the instructions, but i think mel musics does not show up in music selector. But i did put the mel musics in packages but it does not show up for no reason.

**Comment by Areng14** [comment]
install portal stories mel

**Comment by Wilk1910** [comment]
ok

**Comment by TeamSpen210** [comment]
This isn't an issue then.
