### ISSUE TITLE
Valve theme

### ISSUE THREAD

**Issue by slambo311** [BEEmod/BEE2-music#6]
Just good ol' Hazardous Environments would be an amazing track for BEE2, honestly.

**Comment by CardsAndGamesYT** [comment]
I made that a thing just to test it in one of my tests, it didn't fit very well. It's a good song but it's not very good for chambers

**Comment by TeamSpen210** [comment]
Yeah, it doesn't have anything to do with puzzles, and also it's not in P2's files, just part of the intro video.

**Comment by slambo311** [comment]
Yes, but you can take it from half-life 2's files since it's used when you get the HEV suit.

**Comment by CardsAndGamesYT** [comment]
yes thats what i did, but again, it does not fit with testing
