### ISSUE TITLE
Add 'OMG what has he done' as funnel music

### ISSUE THREAD

**Issue by MaxineMaxie** [BEEmod/BEE2-music#7]
### Description of the feature

Add the funnel music on the way to the final battle as funnel music

### Why should this be implemented

I want to replecate the final funnel ride in my maps, but I don't have the music for it

### Additional information

P.S. you should also add There She Is

**Comment by vrad-exe** [comment]
OMG What Has He Done doesn't have a funnel track, it just plays the next part of the main track. Finale Funnel is only used at The Part Where He Kills You.

**Comment by MaxineMaxie** [comment]
I would like that next part of the main track for the music, sorry I wasn't specific 
hope you don't mind

**Comment by vrad-exe** [comment]
That music track is pretty specific to that cutscene, so we probably won't add it.

**Comment by MaxineMaxie** [comment]
Gotcha.
